---
# tasks file for user_init

- name: Create user
  user:
    name: "{{ username }}"
    password: "{{ pwd | password_hash('sha512') }}"

- name: Authorization
  authorized_key:
    user: "{{ username }}"
    key: "{{lookup('file', key)}}"

- name: Disable Password Authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "PasswordAuthentication yes"
    line: "PasswordAuthentication no"

- name: Restart SSH
  service:
    name: sshd
    state: restarted

- name: Create directory
  file:
    path: /opt/dashadir
    state: directory
    owner: "{{ username }}"
    mode: "0755"
